version: "3.7"
services:
  backend:
    build:
      target: development
      context: backend
    environment:
      - DATABASE_DB=werkr
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=/run/secrets/postgres_password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 5000:5000
    secrets:
      - postgres_password
    volumes:
      - ./backend/src:/api/src:ro
      - ./backend/package.json:/api/package.json
      - ./backend/package-lock.json:/api/package-lock.json
    networks:
      - app
      - api
    depends_on:
      - db

  frontend:
    build:
      context: werkr
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./werkr/src:/app/src:ro
    networks:
      - app

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks:
      - api
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_password

networks:
  app: {}
  api: {}

volumes:
  backend-cache: {}
  db-data: {}

secrets:
  postgres_password:
    file: postgres_password.txt
